sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt57-xenial
  - sudo apt-get update

install:
  - sudo apt-get install -y qt-latest

script:
  - . "/opt/qt57/bin/qt57-env.sh"
  - cd qt
  - sh run.sh